class AppLocalizations {
  static const supportedLanguages = ['en', 'si', 'ta'];

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'appTitle': 'බෝඩිම්.lk',
      'createAd': 'Create Ad',
      'editAd': 'Edit Ad',
      'rejectedReason': 'Rejected reason',
      'updateAdPrompt': 'Please update the ad and submit again.',
      'title': 'Title',
      'description': 'Description',
      'priceLabel': 'Price (රු.)',
      'contactNumber': 'Contact number',
      'contact': 'Contact',
      'location': 'Location',
      'posted': 'Posted',
      'call': 'Call',
      'sms': 'SMS',
      'whatsapp': 'WhatsApp',
      'deleteAd': 'Delete Ad',
      'deleteAdConfirmation': 'Are you sure you want to delete this ad?',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'rejectAd': 'Reject Ad',
      'confirmReject': 'Confirm Reject',
      'rejectReasonPrompt': 'Do you want to reject this ad for',
      'adRejectedSuccessfully': 'Ad rejected successfully.',
      'failedToRejectAd': 'Failed to reject ad:',
      'resumeAd': 'Resume Ad',
      'pauseAd': 'Pause Ad',
      'resume': 'Resume',
      'pause': 'Pause',
      'resumeAdPrompt':
          'Do you want to resume this ad and remove it from the home page?',
      'pauseAdPrompt':
          'Do you want to pause this ad and remove it from the home page?',
      'adResumedSuccessfully': 'Ad resumed successfully.',
      'adPausedSuccessfully': 'Ad paused successfully.',
      'failedToResumeAd': 'Failed to resume ad:',
      'failedToPauseAd': 'Failed to pause ad:',
      'noRejectReasonsAvailable':
          'No reject reasons available. Add them in Reject Reasons.',
      'couldNotOpenDialer':
          'Could not open dialer — number copied to clipboard',
      'couldNotOpenMessagingApp':
          'Could not open messaging app — number copied to clipboard',
      'couldNotOpenWhatsApp':
          'Could not open WhatsApp — is WhatsApp installed?',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'removeAll': 'Remove all',
      'post': 'Post',
      'update': 'Update',
      'loadingCategories': 'Loading categories…',
      'noCategoriesAvailable': 'No categories available',
      'selectCategory': 'Select category',
      'anonymousPostNote':
          'If you register before posting, you can edit, delete, pause, and keep track of your ads from My Ads.',
      'pleaseFillAllFields': 'Please fill all fields',
      'invalidContactNumber':
          'Contact number must start with 0 and contain exactly 10 digits.',
      'mustBeLoggedIn': 'You must be logged in to add a post.',
      'noInternetConnection':
          'No internet connection. Please try again when you are online.',
      'unableUploadImages':
          'Unable to upload images. Check your connection and try again.',
      'unableSaveAd':
          'Unable to save the ad. Please check your internet connection and try again.',
      'yourAdUnderReview': 'Your ad is under review.',
      'login': 'Login',
      'welcomeBack': 'Welcome back',
      'createYourAccount': 'Create your account',
      'email': 'Email',
      'password': 'Password',
      'nameOptional': 'Name (optional)',
      'phoneOptional': 'Phone (optional)',
      'dontHaveAccountRegister': 'Don\'t have an account? Register',
      'alreadyHaveAccountLogin': 'Already have an account? Login',
      'continueAnonymously': 'Continue anonymously',
      'invalidCredentialsOrNotRegistered': 'Invalid credentials or not registered',
      'unableSignInAnonymously': 'Unable to sign in anonymously. Please try again.',
      'registrationSuccessful': 'Registration successful',
      'emailAlreadyRegistered': 'Email already registered',
      'filters': 'Filters',
      'clearFilters': 'Clear filters',
      'selectDistrictFirst': 'Select district first',
      'district': 'District',
      'town': 'Town',
      'category': 'Category',
      'all': 'All',
      'collapseFilters': 'Collapse filters',
      'expandFilters': 'Expand filters',
      'myAds': 'My Ads',
      'pleaseLoginToViewYourAds': 'Please login to view your ads.',
      'noMyAdsYet': 'You have not posted any ads yet.',
      'justNow': 'Just now',
      'minuteAgo': '1 minute ago',
      'minutesAgo': '{count} minutes ago',
      'hourAgo': '1 hour ago',
      'hoursAgo': '{count} hours ago',
      'dayAgo': '1 day ago',
      'daysAgo': '{count} days ago',
      'statusPending': 'PENDING',
      'statusRejected': 'REJECTED',
      'statusApproved': 'APPROVED',
      'statusPaused': 'PAUSED',
      'profile': 'Profile',
      'logout': 'Logout',
      'pendingAds': 'Pending Ads',
      'rejectReasons': 'Reject Reasons',
      'categories': 'Categories',
      'contactUs': 'Contact Us',
      'contactUsSubtitle': 'Get in touch with us for any inquiries or support.',
      'emailUs': 'Email',
      'callUs': 'Phone',
      'openEmail': 'Open email app',
      'callAction': 'Call',
      'copy': 'Copy',
      'noListingsMessage':
          'Try adjusting your filters or check back later for new listings.',
      'unableStartAnonymous':
          'Unable to start anonymous session. Please try again.',
      'language': 'Language',
      'english': 'English',
      'sinhala': 'සිංහල',
      'tamil': 'தமிழ்',
      'profileUpdated': 'Profile updated',
      'allFieldsRequired': 'All fields required',
      'passwordsDoNotMatch': 'New passwords do not match',
      'incorrectPassword': 'Current password incorrect or cannot update',
      'passwordChanged': 'Password changed',
      'noNameSet': 'No name set',
      'accountDetails': 'Account details',
      'name': 'Name',
      'phone': 'Phone',
      'saveProfile': 'Save Profile',
      'security': 'Security',
      'currentPassword': 'Current Password',
      'newPassword': 'New Password',
      'confirmNewPassword': 'Confirm New Password',
      'changePassword': 'Change Password',
    },
    'si': {
      'appTitle': 'බෝඩිම්.lk',
      'createAd': 'දැන්වීමක් පළ කරන්න',
      'editAd': 'දැන්වීම සංස්කරණය කරන්න',
      'rejectedReason': 'ප්‍රතික්ෂේප හේතුව',
      'updateAdPrompt': 'කරුණාකර දැන්වීම යාවත්කරණය කර නැවත ඉදිරිපත් කරන්න.',
      'title': 'ශීර්ෂය',
      'description': 'විස්තර',
      'priceLabel': 'මිල (රු.)',
      'contactNumber': 'දුරකථන අංකය',
      'contact': 'සම්බන්ධතාව',
      'location': 'ස්ථානය',
      'posted': 'පළ කළේ',
      'call': 'අමතන්න',
      'sms': 'SMS',
      'whatsapp': 'WhatsApp',
      'deleteAd': 'දැන්වීම මකන්න',
      'deleteAdConfirmation': 'ඔබට මෙම දැන්වීම මකන්න අවශ්‍යද?',
      'delete': 'මකන්න',
      'cancel': 'අවලංගු කරන්න',
      'rejectAd': 'දැන්වීම ප්‍රතික්ෂේප කරන්න',
      'confirmReject': 'ප්‍රතික්ෂේපය තහවුරු කරන්න',
      'rejectReasonPrompt': 'ඔබට මෙම දැන්වීම සඳහා ප්‍රතික්ෂේප කිරීමට අවශ්‍යද',
      'adRejectedSuccessfully': 'දැන්වීම සාර්ථකව ප්‍රතික්ෂේප කරන ලදී.',
      'failedToRejectAd': 'දැන්වීම ප්‍රතික්ෂේප කිරීමට අසමත් විය:',
      'resumeAd': 'දැන්වීම නැවත සක්‍රීය කරන්න',
      'pauseAd': 'දැන්වීම නවතා තබන්න',
      'resume': 'නැවත සක්‍රීය කරන්න',
      'pause': 'නවතා තබන්න',
      'resumeAdPrompt':
          'මෙම දැන්වීම නැවත සක්‍රීය කළ යුතුද සහ මුල් පිටුවට ඇතුලත් කල යුතුද?',
      'pauseAdPrompt':
          'මෙම දැන්වීම නවතා තැබිය යුතුද සහ මුල් පිටුවෙන් ඉවත් කළ යුතුද?',
      'adResumedSuccessfully': 'දැන්වීම නැවත සක්‍රීය කරන ලදී.',
      'adPausedSuccessfully': 'දැන්වීම නවතා තබන ලදී .',
      'failedToResumeAd': 'දැන්වීම නැවත සක්‍රීය කිරීමට අසමත් විය:',
      'failedToPauseAd': 'දැන්වීම නවතා තැබීමට අසමත් විය:',
      'noRejectReasonsAvailable':
          'ප්‍රතික්ෂේප හේතු ලබා ගත නොහැක. Reject Reasons හි ඒවා එකතු කරන්න.',
      'couldNotOpenDialer':
          'ඩයලරය විවෘත කළ නොහැකිය — අංකය ක ලිපී පුවරුවට පිටපත් කරන ලදී',
      'couldNotOpenMessagingApp':
          'පණිවිඩ යෙදුම විවෘත කළ නොහැකිය — අංකය ක ලිපී පුවරුවට පිටපත් කරන ලදී',
      'couldNotOpenWhatsApp':
          'WhatsApp විවෘත කළ නොහැකි විය — WhatsApp ස්ථාපිත කර තිබේද?',
      'gallery': 'ගැලරි',
      'camera': 'කැමරාව',
      'removeAll': 'සියල්ල ඉවත් කරන්න',
      'post': 'පළ කරන්න',
      'update': 'යාවත්කරණය කරන්න',
      'loadingCategories': 'වර්ග පූරණය වෙමින්…',
      'noCategoriesAvailable': 'වර්ග නැත',
      'selectCategory': 'වර්ගය තෝරන්න',
      'anonymousPostNote':
          'ඔබට ලියාපදිංචි නොවී දැන්වීමක් සාදා ගත හැක. නමුත් ඔබ ලියාපදිංචි වුවහොත්, පසුව ඔබේ දැන්වීම් සියල්ල කළමනාකරණය කළ හැක.',
      'pleaseFillAllFields': 'කරුණාකර සියලු ක්ෂේත්‍ර පුරවන්න',
      'invalidContactNumber':
          'දුරකථන අංකය 0 කින් ආරම්භ වන අතර අංක 10ක් තිබිය යුතුය.',
      'mustBeLoggedIn': 'දැන්වීමක් එක් කිරීමට ඔබ ලොග් විය යුතුය.',
      'noInternetConnection':
          'අන්තර්ජාල සම්බන්ධතාවයක් නොමැත. කරුණාකර නැවත උත්සාහ කරන්න.',
      'unableUploadImages':
          'පින්තූර උඩුගත කළ නොහැකි විය. කරුණාකර සබඳතාවය පරීක්ෂා කර නැවත උත්සාහ කරන්න.',
      'unableSaveAd':
          'දැන්වීම සුරකින්න නොහැකි විය. කරුණාකර අන්තර්ජාල සම්බන්ධතාවය පරීක්ෂා කර නැවත උත්සාහ කරන්න.',
      'yourAdUnderReview': 'ඔබගේ දැන්වීම සමාලෝචනයට යටත්ව ඇත.',
      'login': 'ලොග් වන්න',
      'welcomeBack': 'ආදරයෙන් පිළිගනිමු',
      'createYourAccount': 'ඔබේ ගිණුම සාදන්න',
      'email': 'ඊමේල්',
      'password': 'මුරපදය',
      'nameOptional': 'නම (අත්‍යවශ්‍ය නොවේ)',
      'phoneOptional': 'දුරකථනය (අත්‍යවශ්‍ය නොවේ)',
      'dontHaveAccountRegister': 'ගිණුමක් නොමැතිද? ලියාපදිංචි වන්න',
      'alreadyHaveAccountLogin': 'දැනටම ගිණුමක් තිබේද? ලොග් වන්න',
      'continueAnonymously': 'ලියාපදිංචි නොවී ඉදිරියට යන්න',
      'invalidCredentialsOrNotRegistered': 'වලංගු නොවන මුර පද හෝ ලියාපදිංචි කර නොමැත',
      'unableSignInAnonymously': 'ලියාපදිංචි නොවී පිවිසිය නොහැක. කරුණාකර නැවත උත්සාහ කරන්න.',
      'registrationSuccessful': 'ලියාපදිංචිය සාර්ථකයි',
      'emailAlreadyRegistered': 'ඊමේල් ලිපිනය දැනටමත් ලියාපදිංචි වී ඇත',
      'filters': 'පෙරහන්',
      'clearFilters': 'පෙරහන් හිස් කරන්න',
      'selectDistrictFirst': 'පළමුව දිස්ත්‍රික්කය තෝරන්න',
      'district': 'දිස්ත්‍රික්කය',
      'town': 'නගරය',
      'category': 'වර්ගය',
      'all': 'සියල්ල',
      'collapseFilters': 'පෙරහන් හකුලන්න',
      'expandFilters': 'පෙරහන් දිගහරින්න',
      'myAds': 'මගේ දැන්වීම්',
      'pleaseLoginToViewYourAds': 'ඔබේ දැන්වීම් බැලීමට කරුණාකර ලොග් වන්න.',
      'noMyAdsYet': 'ඔබ තවම කිසිදු දැන්වීමක් පළ කර නොමැත.',
      'justNow': 'දැන්',
      'minuteAgo': '1 මිනිත්තියකට පෙර',
      'minutesAgo': '{count} මිනිත්තු පෙර',
      'hourAgo': '1 පැයකට පෙර',
      'hoursAgo': '{count} පැය පෙර',
      'dayAgo': '1 දිනකට පෙර',
      'daysAgo': '{count} දිනකට පෙර',
      'statusPending': 'සලකා බලමින්',
      'statusRejected': 'ප්‍රතික්ෂේප',
      'statusApproved': 'අනුමත',
      'statusPaused': 'නවතා ඇත',
      'profile': 'පැතිකඩ',
      'logout': 'ලොග් අවුට්',
      'pendingAds': 'පියවරේ ඇති දැන්වීම්',
      'rejectReasons': 'ප්‍රතික්ෂේපයේ හේතු',
      'categories': 'වර්ග',
      'contactUs': 'අපව සම්බන්ධ කරගන්න',
      'contactUsSubtitle': 'ඕනෑම ප්‍රශ්නයකට හෝ සහාය සඳහා අපව සම්බන්ධ කරගන්න.',
      'emailUs': 'ඊමේල්',
      'callUs': 'දුරකථනය',
      'openEmail': 'ඊමේල් යෙදුම විවෘත කරන්න',
      'callAction': 'ඇමතුම',
      'copy': 'පිටපත් කරන්න',
      'noListingsMessage':
          'අදාළ දැන්වීම් නොලැබුණි. කරුණාකර පෙරහන් වෙනස් කරන්න හෝ පසුව නැවත බලන්න.',
      'unableStartAnonymous':
          'Anonymous සැසිය ආරම්භ කළ නොහැකි විය. කරුණාකර නැවත උත්සාහ කරන්න.',
      'language': 'භාෂාව',
      'english': 'English',
      'sinhala': 'සිංහල',
      'tamil': 'தமிழ்',
      'profileUpdated': 'පැතිකඩ යාවත්කරණය කරන ලදී',
      'allFieldsRequired': 'සියලු ක්ෂේත්‍ර අවශ්‍ය වේ',
      'passwordsDoNotMatch': 'නව මුරපද නොගැලපේ',
      'incorrectPassword': 'වත්මන් මුරපදය වැරදිය හෝ යාවත්කරණය කළ නොහැක',
      'passwordChanged': 'මුරපදය වෙනස් කරන ලදී',
      'noNameSet': 'නමක් සකසා නොමැත',
      'accountDetails': 'ගිණුම් තොරතුරු',
      'name': 'නම',
      'phone': 'දුරකථනය',
      'saveProfile': 'පැතිකඩ සුරකින්න',
      'security': 'ආරක්ෂාව',
      'currentPassword': 'වත්මන් මුරපදය',
      'newPassword': 'නව මුරපදය',
      'confirmNewPassword': 'නව මුරපදය තහවුරු කරන්න',
      'changePassword': 'මුරපදය වෙනස් කරන්න',
    },
    'ta': {
      'appTitle': 'බෝඩිම්.lk',
      'createAd': 'ஒரு விளம்பரத்தை இடுகையிடவும்',
      'editAd': 'விளம்பரத்தைத் தொகுக்கவும்',
      'rejectedReason': 'நிராகரிக்கப்பட்ட காரணம்',
      'updateAdPrompt':
          'தயவுசெய்து விளம்பரத்தை புதுப்பித்து மீண்டும் சமர்ப்பிக்கவும்.',
      'title': 'தலைப்பு',
      'description': 'விளக்கம்',
      'priceLabel': 'விலை (රු.)',
      'contactNumber': 'தொடர்பு எண்',
      'contact': 'தொடர்பு',
      'location': 'இடம்',
      'posted': 'வெளியிட்டது',
      'call': 'அழைப்பு',
      'sms': 'எஸ்எம்எஸ்',
      'whatsapp': 'WhatsApp',
      'deleteAd': 'விளம்பரத்தை நீக்கு',
      'deleteAdConfirmation': 'இந்த விளம்பரத்தை நீக்க விரும்புகிறீர்களா?',
      'delete': 'நீக்கு',
      'cancel': 'ரத்து செய்யவும்',
      'rejectAd': 'விளம்பரத்தை நிராகரிக்கவும்',
      'confirmReject': 'நிராகரிப்பை உறுதிப்படுத்தவும்',
      'rejectReasonPrompt':
          'இந்த விளம்பரத்தை ... என்ற காரணத்திற்காக நிராகரிக்கவா',
      'adRejectedSuccessfully': 'விளம்பரம் வெற்றிகரமாக நிராகரிக்கப்பட்டது.',
      'failedToRejectAd': 'விளம்பரத்தை நிராகரிக்க முடியவில்லை:',
      'resumeAd': 'விளம்பரத்தை மீண்டும் துவக்கு',
      'pauseAd': 'விளம்பரத்தை இடைநிறுத்து',
      'resume': 'மீண்டும் துவக்கு',
      'pause': 'இடைநிறுத்து',
      'resumeAdPrompt':
          'இந்த விளம்பரத்தை மீண்டும் துவக்க விரும்புகிறீர்களா மற்றும் முகப்புப் பக்கத்திலிருந்து அகற்ற வேண்டும்?',
      'pauseAdPrompt':
          'இந்த விளம்பரத்தை இடைநிறுத்த விரும்புகிறீர்களா மற்றும் முகப்புப் பக்கத்திலிருந்து அகற்ற வேண்டும்?',
      'adResumedSuccessfully': 'விளம்பரம் மீண்டும் துவக்கப்பட்டது.',
      'adPausedSuccessfully': 'விளம்பரம் இடைநிறுத்தப்பட்டது.',
      'failedToResumeAd': 'விளம்பரத்தை மீண்டும் துவக்க முடியவில்லை:',
      'failedToPauseAd': 'விளம்பரத்தை இடைநிறுத்த முடியவில்லை:',
      'noRejectReasonsAvailable':
          'நிராகரிப்பு காரணங்கள் கிடைக்கவில்லை. Reject Reasons இல் அவைகளைச் சேர்க்கவும்.',
      'couldNotOpenDialer':
          'டைலரைத் திறக்க முடியவில்லை — எண்ணை கிளிப்போர்டிற்கு நகல் செய்துவிட்டது',
      'couldNotOpenMessagingApp':
          'செய்தி அனுப்பும் செயலியைத் திறக்க முடியவில்லை — எண்ணை கிளிப்போர்டிற்கு நகல் செய்துவிட்டது',
      'couldNotOpenWhatsApp':
          'WhatsApp ஐத் திறக்க முடியவில்லை — WhatsApp நிறுவப்பட்டுள்ளதா?',
      'gallery': 'கேலரி',
      'camera': 'கேமரா',
      'removeAll': 'அனைத்தையும் நீக்கு',
      'post': 'பதிவிடு',
      'update': 'புதுப்பு',
      'loadingCategories': 'வகைகள் ஏற்றப்படுகிறது…',
      'noCategoriesAvailable': 'வகைகள் இல்லை',
      'selectCategory': 'வகையைத் தேர்ந்தெடுக்கவும்',
      'anonymousPostNote':
          'பதிவேற்றம் செய்யும்முன்பு பதிவு செய்தால், என் விளம்பரங்களில் இருந்து அதைத் திருத்த, நீக்க, நிறுத்த மற்றும் கண்காணிக்க முடியும்.',
      'pleaseFillAllFields': 'அனைத்து புலங்களையும் நிரப்பவும்',
      'invalidContactNumber':
          'தொடர்பு எண் 0-ஆல் துவங்கி சரியாக 10 இலக்கங்களைக் கொண்டிருக்க வேண்டும்.',
      'mustBeLoggedIn':
          'ஒரு பதிவைச் சேர்க்க நீங்கள் உள்நுழைந்திருக்க வேண்டும்.',
      'noInternetConnection': 'இணைய இணைப்பு இல்லை. மீண்டும் முயற்சி செய்க.',
      'unableUploadImages':
          'படங்களை பதிவேற்ற முடியவில்லை. உங்கள் இணைப்பை சரிபார்த்து மீண்டும் முயற்சி செய்யவும்.',
      'unableSaveAd':
          'விளம்பரத்தைச் சேமிக்க முடியவில்லை. உங்கள் இணைய இணைப்பை சரிபார்த்து மீண்டும் முயற்சி செய்யவும்.',
      'yourAdUnderReview': 'உங்கள் விளம்பரம் மதிப்பீட்டில் உள்ளது.',
      'login': 'உள்நுழையவும்',
      'welcomeBack': 'திரும்ப வரவேற்கிறோம்',
      'createYourAccount': 'உங்கள் கணக்கை உருவாக்கவும்',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'nameOptional': 'பெயர் (விருப்பமான)',
      'phoneOptional': 'தொலைபேசி (விருப்பமான)',
      'dontHaveAccountRegister': 'கணக்கு இல்லை? பதிவு செய்யவும்',
      'alreadyHaveAccountLogin': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழையவும்',
      'continueAnonymously': 'மறைமுகமாக தொடரவும்',
      'invalidCredentialsOrNotRegistered': 'தவறான அங்கீகாரங்கள் அல்லது பதிவு செய்யப்படவில்லை',
      'unableSignInAnonymously': 'மறைமுகமாக உள்நுழைய இயலவில்லை. மீண்டும் முயற்சிக்கவும்.',
      'registrationSuccessful': 'பதிவு வெற்றிகரமாக முடிந்தது',
      'emailAlreadyRegistered': 'மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டு உள்ளது',
      'filters': 'வடிகட்டிகள்',
      'clearFilters': 'வடிகட்டிகளை நீக்கு',
      'selectDistrictFirst': 'முதலில் மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
      'district': 'மாவட்டம்',
      'town': 'நகரம்',
      'category': 'வகை',
      'all': 'அனைத்தும்',
      'collapseFilters': 'வடிகட்டிகளை முடக்கு',
      'expandFilters': 'வடிகட்டிகளை விரிவாக்கு',
      'myAds': 'என் விளம்பரங்கள்',
      'pleaseLoginToViewYourAds':
          'உங்கள் விளம்பரங்களைப் பார்க்க தயவுசெய்து உள்நுழையவும்.',
      'noMyAdsYet': 'நீங்கள் இன்னும் எந்த விளம்பரத்தையும் இடவில்லை.',
      'justNow': 'இப்போது',
      'minuteAgo': '1 நிமிடத்திற்கு முன்',
      'minutesAgo': '{count} நிமிடங்களுக்கு முன்னால்',
      'hourAgo': '1 மணிநேரத்திற்கு முன்',
      'hoursAgo': '{count} மணிநேரங்களுக்கு முன்னால்',
      'dayAgo': '1 நாளிற்கு முன்',
      'daysAgo': '{count} நாட்களுக்கு முன்னால்',
      'statusPending': 'நிலுவையில்',
      'statusRejected': 'நிராகரிக்கப்பட்டது',
      'statusApproved': 'அங்கீகரிக்கப்பட்டது',
      'statusPaused': 'இடைநிறுத்தப்பட்டது',
      'profile': 'சுயவிவரம்',
      'logout': 'வெளியேறு',
      'pendingAds': 'நிலுவையில் உள்ள விளம்பரங்கள்',
      'rejectReasons': 'நிராகரிப்பு காரணங்கள்',
      'categories': 'வகைகள்',
      'contactUs': 'எங்களை தொடர்பு கொள்ளுங்கள்',
      'contactUsSubtitle': 'ஏதேனும் கேள்விகள் அல்லது ஆதரவிற்கு எங்களை தொடர்பு கொள்ளுங்கள்.',
      'emailUs': 'மின்னஞ்சல்',
      'callUs': 'தொலைபேசி',
      'openEmail': 'மின்னஞ்சல் பயன்பாட்டைத் திற',
      'callAction': 'அழைப்பு',
      'copy': 'நகலெடு',
      'noListingsMessage':
          'பொருந்தும் விளம்பரங்கள் இல்லை. உங்கள் வடிகட்டிகளை மாற்றவும் அல்லது பின்னர் மீண்டும் முயற்சிக்கவும்.',
      'unableStartAnonymous':
          'அறியப்படாத அமர்வைக் தொடங்க முடியません. மீண்டும் முயற்சிக்கவும்.',
      'language': 'மொழி',
      'english': 'English',
      'sinhala': 'සිංහල',
      'tamil': 'தமிழ்',
      'profileUpdated': 'சுயவிவரம் புதுப்பிக்கப்பட்டது',
      'allFieldsRequired': 'அனைத்து புலங்களும் தேவை',
      'passwordsDoNotMatch': 'புதிய கடவுச்சொற்கள் பொருந்தவில்லை',
      'incorrectPassword':
          'தற்போதைய கடவுச்சொல் தவறானது அல்லது புதுப்பிக்க முடியவில்லை',
      'passwordChanged': 'கடவுச்சொல் மாற்றப்பட்டது',
      'noNameSet': 'பெயர் அமைக்கப்படவில்லை',
      'accountDetails': 'கணக்கு விவரங்கள்',
      'name': 'பெயர்',
      'phone': 'தொலைபேசி',
      'saveProfile': 'சுயவிவரத்தை சேமி',
      'security': 'பாதுகாப்பு',
      'currentPassword': 'தற்போதைய கடவுச்சொல்',
      'newPassword': 'புதிய கடவுச்சொல்',
      'confirmNewPassword': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'changePassword': 'கடவுச்சொல்லை மாற்று',
    },
  };

  static String translate(String languageCode, String key) {
    return _translations[languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }
}
